version: '3.8'

services:
  api:
    build: 
      context: .
      target: development
    command: poetry run uvicorn api.main:app --host 0.0.0.0 --port 54269 --reload
    environment:
      - ENVIRONMENT=development

  static:
    build: 
      context: .
      target: development
    command: poetry run uvicorn api.static_server:app --host 0.0.0.0 --port 56129 --reload
    environment:
      - ENVIRONMENT=development
    ports:
      - "56129:56129"

networks:
  tutor_network:
    driver: bridge