version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    command: poetry run uvicorn api.main:app --host 0.0.0.0 --port 54321 --reload
    ports:
      - "54321:54321"
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=sk-dummy-key

  static:
    build: 
      context: .
      target: development
    command: poetry run uvicorn api.static_server:app --host 0.0.0.0 --port 54322 --reload
    environment:
      - ENVIRONMENT=development
      - API_PORT=54321
    ports:
      - "54322:54322"

networks:
  tutor_network:
    driver: bridge