version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: development
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 54321 --reload
    ports:
      - "54321:54321"
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=sk-dummy-key

  static:
    build: 
      context: ./backend  # Context is backend, uses backend/Dockerfile
      target: development
    command: poetry run uvicorn app.core.static_server:app --host 0.0.0.0 --port 54322 --reload
    volumes:
      - ./frontend/public/templates:/app/static_frontend_templates:ro # Mount templates
    environment:
      - ENVIRONMENT=development
      - API_PORT=54321
    ports:
      - "54322:54322"

networks:
  tutor_network:
    driver: bridge