version: '3.8'

services:
  api:
    build: 
      context: .
      target: development
    command: poetry run uvicorn api.main:app --host 0.0.0.0 --port 52518 --reload --forwarded-allow-ips="*" --proxy-headers
    volumes:
      - .:/app
      - poetry-cache:/root/.cache/pypoetry
    ports:
      - "52518:52518"
    environment:
      - STATIC_SERVER_URL=http://localhost:57839
      - TEMPORAL_HOST=temporal:7233
      - ENVIRONMENT=development
    depends_on:
      - temporal
    networks:
      - tutor_network

  static:
    build: 
      context: .
      target: development
    command: poetry run uvicorn api.static_server:app --host 0.0.0.0 --port 57839 --reload --forwarded-allow-ips="*" --proxy-headers
    volumes:
      - .:/app
      - poetry-cache:/root/.cache/pypoetry
    ports:
      - "57839:57839"
    environment:
      - ENVIRONMENT=development
    networks:
      - tutor_network

  temporal:
    image: temporalio/auto-setup:1.22.3
    ports:
      - "7233:7233"
      - "7234:7234"
      - "7235:7235"
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - tutor_network

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.3
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - tutor_network

  temporal-web:
    image: temporalio/ui:2.21.3
    ports:
      - "8088:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8088
    depends_on:
      - temporal
    networks:
      - tutor_network

volumes:
  poetry-cache:

networks:
  tutor_network:
    driver: bridge